# Site settings
title: < techno-baba />
author_full_name: Sandeep Kumar
email: kumarsandeep91@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello, I'm Sandeep, CEO & Founder of Russet Technology Solutions LLP.. Check out my projects on GitHub
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sandeepsihari.com/" # the base hostname & protocol for your site
twitter_username: kumarsandeep91
github_username:  kumarsandeep91
facebook_profile: sandeepsihari
instagram_profile: sandeepsihari
linkedin_profile: https://www.linkedin.com/in/sandeepsihari
russet_url: http://russet.in
russet_name: Russet Technology Solutions LLP
timezone: Asia/Kolkata
# Build settings
markdown: kramdown
highlighter: null #pygments
lsi: false
safe: false
