import React, { useRef, useEffect } from "react";
import Head from "next/head";

import Typed from "typed.js";

export default function Home() {
	// Ref https://jsfiddle.net/mattboldt/60h9an7y/
	const el = useRef(null);
	const typed = useRef(null);

	useEffect(() => {
		const options = {
			strings: [
				'<span class="color-primary">Full-time web developer.</span>',
				'<span class="color-secondary">Self-proclaimed master chef.</span>',
				'<span class="color-tertiary">Part-time Netflix, Prime video addict.</span>',
			],
			typeSpeed: 60,
			backSpeed: 30,
			backDelay: 1500,
			loop: true,
		};

		typed.current = new Typed(el.current, options);

		return () => {
			typed.current.destroy();
		};
	}, []);

	return (
		<>
			<Head>
				<title>Sandeep Sihari</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<section className="global-padding text-align-center">
					<h1 className="main-heading">
						Hi, I'm <span className="color-highlight">Sandeep</span>
					</h1>
					<h4 className="typewriter">
						<span ref={el} />
					</h4>

					<div className="flex center gap-1 cta">
						<button className="btn-secondary btn-rounded">See my stuff</button>
						<button className="btn-secondary-outline btn-rounded">
							Say hello
						</button>
					</div>
				</section>
			</main>
		</>
	);
}
